### ISSUE TITLE
What one to download?

### ISSUE THREAD

**Issue by killerrook** [naz664/ArrowOS_gsi#3]
Q. What is the difference between bvn and bgn

Q. What is the difference between slim and others

Q. What is the difference between a64 and arm64? Are they both the same

Thanks for your help.

**Comment by naz664** [comment]
Information about what type of GSI it is

<ARCH>_xyZ

<ARCH> can either be arm, a64 or arm64
x can either be a or b
y can either be v, o, g or f
Z can be N or S

b = a/b
a = a-only

g = gapps
o = gapps-go
v = vanilla (no gapps included)
f = floss (free & open source apps instead gapps)

N = no superuser
S = superuser included

Slim = a lite build to fit devices with smaller partition
Slim builds are usually read only

Vndklite = Extras libs and stuff for lite vendors (Devices launched with 8.0)
Some device need vndklite varient to get camera and all fully working
