### ISSUE TITLE
Some parts are not translated into Japanese.

### ISSUE THREAD

**Issue by reindex-ot** [naz664/ArrowOS_gsi#4]
In the ArrowOS Official Crowdin, the translated parts are not translated when it comes to GSI.

Example: (English→Japanese)
Radio info → 無線情報
Tap to show info → タップで情報を表示
Screenshot Sound → スクリーンショットの音
Show volume panel on left → 音量パネルを左側に表示
ArrowOS version → ArrowOS バージョン
Device → デバイス
Maintainer → メンテナ

![IMG_20230526_083435](https://github.com/naz664/ArrowOS_gsi/assets/32851879/593eb5f4-13be-4742-b99c-17ecb32d95af)
![IMG_20230526_083412](https://github.com/naz664/ArrowOS_gsi/assets/32851879/b95ea051-8e89-4f3d-8309-473132a8441b)

**Comment by naz664** [comment]
Need source side changes
